[package]
name = "ykcode-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "ykcode-backend"
path = "src/main.rs"

[dependencies]
ykcode-core.workspace = true
ykcode-ui = { workspace = true, features = ["ssr"] }
ykcode-server.workspace = true
leptos = { workspace = true, features = ["ssr"] }
leptos_axum.workspace = true
leptos_meta = { workspace = true, features = ["ssr"] }
leptos_router = { workspace = true, features = ["ssr"] }
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true
serde_json.workspace = true
anyhow.workspace = true
