[package]
name = "ykcode-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
ssr = ["dep:leptos_axum", "dep:leptos_config", "leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]
hydrate = ["leptos/hydrate", "dep:gloo-net", "dep:web-sys", "dep:js-sys", "dep:wasm-bindgen"]

[dependencies]
ykcode-core.workspace = true
ykcode-export.workspace = true
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }
leptos_config = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
gloo-net = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
